D16_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('mmorpg.urls')),
 ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mmorpg/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .views import *

urlpatterns = [
    path('profile/', profile, name='profile'),
    path('profile/edit', edit_profile, name='edit_profile'),
    # Category
    path('categories/', views.category_list_view, name='mmorpg/category/vcategory_list'),
    # path('category/create/', create_category, name='mmorpg/category/create_category'),
    # Post
    path('', post_list, name='post_list'),
    # path('post/create', PostCreate.as_view(), name='mmorpg/post_create'),
    # path('post/<int:pk>/', PostDetail.as_view(), name='mmorpg/post_detail'),
    # path('post/<int:pk>/edit/', PostEdit.as_view(), name='post_edit'),
    # path('post/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
]
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mmorpg/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='media/profile_photos', null=True, blank=True)
    telegram = models.CharField('Telegram', max_length=32, default='no telegram')
    discord = models.CharField('Discord', max_length=32, default='no discord')
    about_me = RichTextUploadingField()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    name = models.CharField('Category name', max_length=16, unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    category = models.ManyToManyField("Category", through='PostCategory',)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = RichTextUploadingField()

    def __str__(self):
        return self.title


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

mmorpg/forms.py
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Post, Category


class UserForm(forms.ModelForm):
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))
    email = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('photo', 'telegram', 'discord', 'about_me')


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {
            'name': 'Category name'
        }

mmorpg/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from .models import *
from .forms import UserForm, ProfileForm, CategoryForm
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from .models import Post


def category_list_view(request):
    categories = Category.objects.all()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('category_list')
    else:
        form = CategoryForm()

    context = {
        'categories': categories,
        'form': form,
    }
    return render(request, 'mmorpg/category/category_list.html', context)

@login_required
def edit_profile(request):
    user = request.user
    profile = Profile.objects.get_or_create(user=user)[0]

    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('profile')
    else:
        user_form = UserForm(instance=user)
        profile_form = ProfileForm(instance=profile)

    return render(request, 'mmorpg/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })


@login_required
def profile(request):
    user = request.user
    profile = Profile.objects.get(user=user)
    user_form = UserForm(instance=user)
    profile_form = ProfileForm(instance=profile)
    context = {'profile': profile, 'profile_form': profile_form, 'user_form': user_form}
    return render(request, 'mmorpg/profile.html', context)


# class PostList(ListView):
#     model = Post
#     template_name = 'mmorpg/post_list.html'
#     context_object_name = 'post'
def post_list(request):
    posts = Post.objects.all()
    context = {'posts': posts}
    return render(request, 'mmorpg/post_list.html', context)

templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    {% include 'material/includes/material_css.html' %}
    {% include 'material/includes/material_js.html' %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css">

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">My Site</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="container py-4">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

templates/mmorpg/category/category_list.html
{% extends "index.html" %}

{% block content %}
  <h1>Categories</h1>
  <ul>
    {% for category in categories %}
      <li>{{ category.name }} <a href="{% url 'category_delete' category.id %}">Delete</a></li>
    {% empty %}
      <li>No categories yet.</li>
    {% endfor %}
  </ul>

  <h2>Add a Category</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/mmorpg/category/create_category.html
{% extends "index.html" %}

{% block content %}
  <h1>Create Category</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/mmorpg/category/edit_category.html
{% extends "index.html" %}

{% block content %}
  <h1>Edit Category</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/mmorpg/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/mmorpg/edit_profile.html
{% extends "index.html" %}
{% block content %}
  <h1>Edit Profile</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {{ profile_form.media }}

    <div class="row">
        <div class="col">
            {{ user_form.username.label_tag }}
            {{ user_form.username }}
        </div>
        <div class="col">
            {{ user_form.email.label_tag }}
            {{ user_form.email }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ user_form.first_name.label_tag }}
            {{ user_form.first_name }}
        </div>
        <div class="col">
            {{ user_form.last_name.label_tag }}
            {{ user_form.last_name }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ profile_form.telegram.label_tag }}
            {{ profile_form.telegram }}
        </div>
        <div class="col">
            {{ profile_form.discord.label_tag }}
            {{ profile_form.discord }}
        </div>
    </div>
<p>
    {{ profile_form.photo.label_tag }}
    {{ profile_form.photo }}
</p>
<p>
    {{ profile_form.about_me.label_tag }}
    {{ profile_form.about_me }}
</p>

    <button type="submit" class="btn btn-primary">Save changes</button>
  </form>
{% endblock %}

templates/mmorpg/post_create.html
{% extends "index.html" %}

{% block content %}
  <h1>{{ title }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}
{#{% block content %}#}
{#  <h1>Создать пост</h1>#}
{#  <hr>#}
{#  <form action="" method="post">#}
{#    {% csrf_token %}#}
{#    <div class="form-group">#}
{#      <label for="{{ form.title.id_for_label }}">Заголовок</label>#}
{#      {{ form.title }}#}
{#    </div>#}
{#    <div class="form-group">#}
{#      <label for="{{ form.body.id_for_label }}">Текст</label>#}
{#      {{ form.body }}#}
{#    </div>#}
{#    <div class="form-group">#}
{#      <label for="{{ form.category.id_for_label }}">Категории</label>#}
{#      {{ form.category }}#}
{#    </div>#}
{#    <button type="submit" class="btn btn-primary">Сохранить</button>#}
{#  </form>#}
{#{% endblock content %}#}

templates/mmorpg/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object }}"?</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

templates/mmorpg/post_detail.html
{% extends "index.html" %}
{% load material_form %}
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>

{% block title %}
Пост
{% endblock title %}


{% block content %}
<h1>Post {{ post.title }} #{{ post.id }}</h1>
Автор - {{ post.author.user }}
<br>
Время поста - {{ post.time_in }}
<br>
Тип поста - {{ post.publication_type }}
<br>
Заголовок - {{ post.post_title }}
<br>
Текст - {{ post.post_text }}
<br>
Рейтинг - {{ post.rating }}

{% endblock content %}

templates/mmorpg/post_edit.html
{% extends "index.html" %}

{% block content %}
  <h1>Создать пост</h1>
  <hr>
  <form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="{{ form.title.id_for_label }}">Заголовок</label>
      {{ form.title }}
    </div>
    <div class="form-group">
      <label for="{{ form.body.id_for_label }}">Текст</label>
      {{ form.body }}
    </div>
    <div class="form-group">
      <label for="{{ form.category.id_for_label }}">Категории</label>
      {{ form.category }}
    </div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
  </form>
{% endblock content %}

templates/mmorpg/post_list.html
{% extends 'index.html' %}

{% block title %}
News
{% endblock title %}

{% block content %}
<h1>All Post</h1>
<hr>


     <h1>All Posts</h1>
  <ul>
    {% for post in posts %}
      <li>{{ post.title }}</li>
    {% endfor %}
  </ul>



    {% if posts %}
        <table>
            <tr>
                <td>Заголовок</td>
               <td>Статья</td>
               <td>Дата публикации</td>
{#               {% if perms.newssj.change_post or perms.newssj.delete_post %}#}
{#               <td>Действия</td>#}
{#               {% endif %}#}
           </tr>

           {% for post in posts %}
           <tr>
               <td>{{ post.author.id }}</td>
               <td>{{ post.title }}</td>
               <td>{{ post.body }}</td>
               <td>{{ post.category }}</td>
{#               <td>#}
{#                   {% if perms.newssj.change_post %}#}
{#                   <a href="{% url 'edit_news' pk=new.id %}">Изменить</a>#}
{#                   {% endif %}#}
{#                   {% if perms.newssj.delete_post %}#}
{#                   <a href="{% url 'delete_news' pk=new.id %}">Удалить</a>#}
{#                   {% endif %}#}
{#               </td>#}
           </tr>
           {% endfor %}
       </table>
   {% else %}
{#</div>#}

       <h2>Новостей нет!</h2><td>{{ postik.author }}</td>
   {% endif %}
    {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; первая</a>
        ...
        <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
    {% endif %}

    <span class="current">
        Страница {{ page_obj.number }}
    </span>

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        ...
        <a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
    {% endif %}

{% endblock content %}

templates/mmorpg/profile.html
{% extends 'index.html' %}



{% block content %}
    <img src="{{ profile.photo.url }}" alt="Profile photo" class="rounded" style="width: 75px; height: auto">
    <h1>{{ user.username }}</h1>
    <div class="row">
        <div class="col">
            {{ user_form.username.label_tag }}
            {{ user_form.username }}
        </div>
        <div class="col">
            {{ user_form.email.label_tag }}
            {{ user_form.email }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ user_form.first_name.label_tag }}
            {{ user_form.first_name }}
        </div>
        <div class="col">
            {{ user_form.last_name.label_tag }}
            {{ user_form.last_name }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ profile_form.telegram.label_tag }}
            {{ profile_form.telegram }}
        </div>
        <div class="col">
            {{ profile_form.discord.label_tag }}
            {{ profile_form.discord }}
        </div>
    </div>
    {{ profile_form.about_me.label_tag }}
    <div class="about-me" style="width: 50%; word-wrap: break-word;">
  {{ profile.about_me|safe }}
    {{ category.all }}
</div>


{% endblock %}